version: '3.1'

services:
  data_base:
    container_name: db_mysql
    image: jorgelts/mysql:5.7
    ports:
      - 3306:3306
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
         - "./volume/data:/var/lib/mysql"
         - "./volume/config/custom_config.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: root
